### ISSUE TITLE
Robot does not move

### ISSUE THREAD

**Issue by VictorLamoine** [ros-industrial-attic/bezier_examples#2]
There are some calls to MoveIt but the robot does not move in RViz.

**Comment by nlimpert** [comment]
The file `fanuc_m10ia_moveit_config_melodic/config/ros_controllers.yaml` seems to need a proper `controller_list` defined:
```
controller_list:
  - name: ""
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]
```

When I change it to this content the robot starts moving.
Do you think that's the issue? If so I'll create a PR.
